# Generated by Django 5.2.4 on 2025-07-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='imageUrl',
            field=models.URLField(default='https://i.sstatic.net/y9DpT.jpg'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='imageUrl',
            field=models.URLField(default='https://i.sstatic.net/y9DpT.jpg'),
        ),
    ]
