# Generated by Django 5.2.4 on 2025-07-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_question_imageurl_quiz_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='imageUrl',
            field=models.URLField(default='https://thumbs.dreamstime.com/b/pondering-emoticon-single-finger-thumb-resting-chin-thinking-wondering-ponder-emoticon-103989079.jpg'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='imageUrl',
            field=models.URLField(default='https://thumbs.dreamstime.com/b/pondering-emoticon-single-finger-thumb-resting-chin-thinking-wondering-ponder-emoticon-103989079.jpg'),
        ),
    ]
